[project]
name = "agent"
version = "0.1.0"
description = "SRE Agent"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "langchain-google-genai>=2.1.4",
    "mcp-use>=1.2.12",
    "uvicorn>=0.34.2",
]
